# Generated by Django 6.0.3 on 2026-03-27 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection', models.TextField(verbose_name='Objection du médecin')),
                ('response', models.TextField(verbose_name='Réponse du délégué')),
                ('niveau_alia_input', models.CharField(choices=[('Débutant', 'Débutant'), ('Junior', 'Junior'), ('Confirmé', 'Confirmé'), ('Expert', 'Expert')], default='Junior', max_length=20, verbose_name='Niveau ALIA saisi')),
                ('quality', models.CharField(max_length=20, verbose_name='Qualité')),
                ('overall_score', models.FloatField(verbose_name='Score global ALIA')),
                ('score_scientific', models.FloatField(verbose_name='Score scientifique')),
                ('score_clarity', models.FloatField(verbose_name='Score clarté')),
                ('score_objection', models.FloatField(verbose_name='Score objection')),
                ('sentiment', models.CharField(max_length=20, verbose_name='Sentiment')),
                ('niveau_alia_pred', models.CharField(max_length=20, verbose_name='Niveau ALIA prédit')),
                ('visit_format', models.CharField(max_length=20, verbose_name='Format visite')),
                ('conformite', models.BooleanField(verbose_name='Conformité')),
                ('acrv_score', models.IntegerField(default=0, verbose_name='Score A-C-R-V')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date analyse')),
            ],
            options={
                'verbose_name': 'Analyse NLP',
                'verbose_name_plural': 'Analyses NLP',
                'ordering': ['-created_at'],
            },
        ),
    ]
